repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: name-tests-test
    -   id: forbid-new-submodules
    -   id: check-json
    -   id: check-yaml
        args: [.pre-commit-config.yaml]
    -   id: check-toml
        args: [pyproject.toml]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py311-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.14.0]
        args: [--ignore, "E501,W503"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
